FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase

    Mimic_Habayose:
      id: 5
      type: Mimic
  Passive:
    transitions:
      FixStand: F1.on_pressed # キーボード操作時: 1
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,
      1,1,
      1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,
      3,3,
      3,3,3,3,3,3,3,
    ]
  FixStand:
    transitions:
      Passive: back.on_pressed # キーボード操作時: S（緊急停止）
      Velocity: F2.on_pressed # キーボード操作時: 3
      Mimic_Habayose: Y.on_pressed # キーボード操作時: 4
    kp: [
      100, 100, 100, 150, 40, 40,
      100, 100, 100, 150, 40, 40,
      200,200,200,
      40,40,40,40,40,
      100,100,
      40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,
      4,4,
      10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0.35, 0.18,0,0.87,0,
        0,0,
        0.35,-0.18,0,0.87,0,
      ]
    ]
  Velocity:
    transitions:
      Passive: back.on_pressed # キーボード操作時: S（緊急停止）
      FixStand: F1.on_pressed # キーボード操作時: 1
      Mimic_Habayose: Y.on_pressed # キーボード操作時: 4
    policy_dir: config/policy/velocity/v0

  Mimic_Habayose:
    transitions:
      Passive: back.on_pressed # キーボード操作時: S（緊急停止）
      FixStand: F1.on_pressed # キーボード操作時: 1
      Velocity: F2.on_pressed # キーボード操作時: 3

    motion_file: config/policy/mimic/habayose_0014/params/habayose_0014.npz
    policy_dir: config/policy/mimic/habayose_0014_opt/
    end_state: Velocity
    time_start: 0.0
    time_end: 500.0
